# Generated by Django 4.2.7 on 2023-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_office', models.CharField(max_length=50)),
                ('project_stage', models.CharField(max_length=50)),
                ('GNI', models.CharField(max_length=50)),
                ('ESB', models.CharField(max_length=50)),
                ('WINDOW', models.CharField(max_length=50)),
                ('CWI', models.CharField(max_length=50)),
                ('OIL_BOILER', models.CharField(max_length=50)),
                ('OIL_TANK', models.CharField(max_length=50)),
                ('EWI', models.CharField(max_length=50)),
                ('PLUMBING', models.CharField(max_length=50)),
                ('IWI', models.CharField(max_length=50)),
                ('AIRTIGHTNESS', models.CharField(max_length=50)),
                ('RTV', models.CharField(max_length=50)),
                ('MEV', models.CharField(max_length=50)),
                ('ATTIC', models.CharField(max_length=50)),
                ('DRAUGHTPROOFING', models.CharField(max_length=50)),
            ],
        ),
    ]
