# Generated by Django 4.2.7 on 2023-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='project_office',
        ),
    ]
