# Generated by Django 4.2.7 on 2023-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0002_remove_projectdetails_project_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='AIRTIGHTNESS',
            new_name='AIRTIGHTNESS_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='ATTIC',
            new_name='ATTIC_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='CWI',
            new_name='CWI_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='DRAUGHTPROOFING',
            new_name='DRAUGHTPROOFING_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='ESB',
            new_name='ESB_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='EWI',
            new_name='EWI_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='GNI',
            new_name='GNI_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='IWI',
            new_name='IWI_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='MEV',
            new_name='MEV_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='OIL_BOILER',
            new_name='OIL_BOILER_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='OIL_TANK',
            new_name='OIL_TANK_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='PLUMBING',
            new_name='PLUMBING_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='RTV',
            new_name='RTV_STATUS',
        ),
        migrations.RenameField(
            model_name='projectdetails',
            old_name='WINDOW',
            new_name='WINDOW_STATUS',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_office',
            field=models.CharField(default='WHS', max_length=20),
        ),
    ]
