# Generated by Django 4.2.7 on 2023-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0003_rename_airtightness_projectdetails_airtightness_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtightnessStatusID',
            fields=[
                ('airtightness_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('airtightness_status_name', models.CharField(max_length=50)),
                ('airtightness_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AtticStatusID',
            fields=[
                ('attic_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('attic_status_name', models.CharField(max_length=50)),
                ('attic_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenceTypeID',
            fields=[
                ('correspondence_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('correspondence_name', models.CharField(max_length=100)),
                ('correspondence_abbreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CwiStatusID',
            fields=[
                ('cwi_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cwi_status_name', models.CharField(max_length=50)),
                ('cwi_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DraughtProofingStatusID',
            fields=[
                ('draught_proofing_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('draught_proofing_status_name', models.CharField(max_length=50)),
                ('draught_proofing_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EwiStatus',
            fields=[
                ('ewi_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ewi_status_name', models.CharField(max_length=50)),
                ('ewi_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IwiStatusID',
            fields=[
                ('iwi_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('iwi_status_name', models.CharField(max_length=50)),
                ('iwi_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MevStatusID',
            fields=[
                ('mev_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mev_status_name', models.CharField(max_length=50)),
                ('mev_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OilBoilerStatusID',
            fields=[
                ('oil_boiler_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('oil_boiler_status_name', models.CharField(max_length=50)),
                ('oil_boiler_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OilTankStatusID',
            fields=[
                ('oil_tank_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('oil_tank_status_name', models.CharField(max_length=50)),
                ('oil_tank_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlumbingStatusID',
            fields=[
                ('plumbing_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('plumbing_status_name', models.CharField(max_length=50)),
                ('plumbing_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RtvStatusID',
            fields=[
                ('rtv_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rtv_status_name', models.CharField(max_length=50)),
                ('rtv_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WindowStatusID',
            fields=[
                ('window_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('window_status_name', models.CharField(max_length=50)),
                ('window_status_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
