# Generated by Django 4.2.7 on 2023-12-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0004_airtightnessstatusid_atticstatusid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EwiStatus',
            new_name='EwiStatusID',
        ),
    ]
