# Generated by Django 4.2.7 on 2023-12-07 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0005_rename_ewistatus_ewistatusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
