# Generated by Django 4.2.7 on 2023-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0006_alter_projectdetails_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsbStages',
            fields=[
                ('esb_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('esb_stage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GniStages',
            fields=[
                ('gni_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('gni_stage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStages',
            fields=[
                ('preoject_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_stage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
