# Generated by Django 4.2.7 on 2023-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0007_esbstages_gnistages_projectstages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstages',
            name='project_stage_name',
            field=models.CharField(max_length=50),
        ),
    ]
