# Generated by Django 4.2.7 on 2023-12-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0008_alter_projectstages_project_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstages',
            name='project_stage_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
