# Generated by Django 4.2.7 on 2024-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0009_alter_projectstages_project_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='airtightness_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='attic_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='cwi_correpondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='draughtproofing_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='ewi_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='iwi_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='mev_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='oil_boiler_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='oil_tank_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='plumbing_correpondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='rtv_correspondence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='window_correspondece_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectstages',
            name='project_stage_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
