# Generated by Django 4.2.7 on 2024-01-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0010_projectdetails_airtightness_correspondence_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='window_correspondece_id',
            new_name='window_correspondence_id',
        ),
    ]
