# Generated by Django 4.2.7 on 2024-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0011_rename_window_correspondece_id_projectdetails_window_correspondence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProjectStages',
            fields=[
                ('project_stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_stage_name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='projectstages',
            old_name='preoject_stage_id',
            new_name='project_stage_id',
        ),
    ]
