# Generated by Django 5.0.2 on 2024-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0012_companyprojectstages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStages',
        ),
        migrations.AlterField(
            model_name='esbstages',
            name='esb_stage_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gnistages',
            name='gni_stage_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
