# Generated by Django 5.0.2 on 2024-02-13 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0013_delete_projectstages_alter_esbstages_esb_stage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcStages',
            fields=[
                ('qc_stage_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('qc_stage_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='QC_STATUS',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
