# Generated by Django 5.0.2 on 2024-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0014_qcstages_projectdetails_qc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowstatusid',
            name='window_status_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
