# Generated by Django 5.0.2 on 2024-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0015_alter_windowstatusid_window_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='WINDOW_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='windowstatusid',
            name='window_status_name',
            field=models.CharField(max_length=50),
        ),
    ]
