# Generated by Django 5.0.2 on 2024-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0016_alter_projectdetails_window_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='AIRTIGHTNESS_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ATTIC_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='CWI_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='DRAUGHTPROOFING_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='EWI_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='IWI_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='MEV_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='OIL_BOILER_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='OIL_TANK_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='PLUMBING_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='RTV_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
