# Generated by Django 5.1.1 on 2024-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0017_alter_projectdetails_airtightness_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='QC_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
