# Generated by Django 5.1.1 on 2024-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0018_alter_projectdetails_qc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='Project_Manager',
            field=models.CharField(default='Blank', max_length=50),
        ),
    ]
