# Generated by Django 5.1.1 on 2024-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0019_projectdetails_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_manager', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
