# Generated by Django 5.1.1 on 2024-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0020_projectmanagers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagers',
            name='project_manager',
            field=models.CharField(max_length=50),
        ),
    ]
