# Generated by Django 5.1.1 on 2024-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0022_alter_projectmanagers_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='Project_Manager',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
