# Generated by Django 5.1.1 on 2024-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0023_alter_projectdetails_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='Project_Manager',
            field=models.CharField(max_length=50),
        ),
    ]
