# Generated by Django 5.1.1 on 2025-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0026_alter_projectdetails_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='ESB_STATUS',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='GNI_STATUS',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='airtightness_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='attic_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='cwi_correpondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='draughtproofing_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='ewi_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='iwi_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='mev_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='oil_boiler_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='oil_tank_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='plumbing_correpondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='rtv_correspondence_id',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='window_correspondence_id',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='CO_INVOICES_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='DCV_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='DOW_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='FINAL_BER_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='FLOOR_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='MVHR_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='SOLAR_STATUS',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_office',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
