# Generated by Django 5.1.1 on 2025-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0027_remove_projectdetails_esb_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_number',
            field=models.CharField(max_length=20),
        ),
    ]
