# Generated by Django 5.1.1 on 2025-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0028_alter_projectdetails_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoInvoicesStatusID',
            fields=[
                ('co_invoices_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('co_invoices_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DCVStatusID',
            fields=[
                ('dcv_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('dcv_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DowStatusID',
            fields=[
                ('dow_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('dow_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinalBerStatusID',
            fields=[
                ('final_ber_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('final_ber_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FloorStatusID',
            fields=[
                ('floor_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('floor_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MVHRStatusID',
            fields=[
                ('mvhr_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mvhr_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolarStatusID',
            fields=[
                ('solar_status_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('solar_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CorrespondenceTypeID',
        ),
        migrations.DeleteModel(
            name='EsbStages',
        ),
        migrations.DeleteModel(
            name='GniStages',
        ),
        migrations.RemoveField(
            model_name='airtightnessstatusid',
            name='airtightness_status_status',
        ),
        migrations.RemoveField(
            model_name='atticstatusid',
            name='attic_status_status',
        ),
        migrations.RemoveField(
            model_name='cwistatusid',
            name='cwi_status_status',
        ),
        migrations.RemoveField(
            model_name='draughtproofingstatusid',
            name='draught_proofing_status_status',
        ),
        migrations.RemoveField(
            model_name='ewistatusid',
            name='ewi_status_status',
        ),
        migrations.RemoveField(
            model_name='iwistatusid',
            name='iwi_status_status',
        ),
        migrations.RemoveField(
            model_name='mevstatusid',
            name='mev_status_status',
        ),
        migrations.RemoveField(
            model_name='oilboilerstatusid',
            name='oil_boiler_status_status',
        ),
        migrations.RemoveField(
            model_name='oiltankstatusid',
            name='oil_tank_status_status',
        ),
        migrations.RemoveField(
            model_name='plumbingstatusid',
            name='plumbing_status_status',
        ),
        migrations.RemoveField(
            model_name='rtvstatusid',
            name='rtv_status_status',
        ),
        migrations.RemoveField(
            model_name='windowstatusid',
            name='window_status_status',
        ),
    ]
