# Generated by Django 5.1.1 on 2025-05-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0030_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
