# Generated by Django 5.1.1 on 2025-05-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0034_delete_customuser'),
    ]

    operations = [
    ]
