# Generated by Django 5.1.1 on 2025-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procoreapi', '0036_populate_email_from_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_offices', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
